specs.dir: /specs/
spring:
  datasource:
    url: jdbc:mysql://192.168.1.224:3306/studentmanager?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true